### ISSUE TITLE
Internationalize the app

### ISSUE THREAD

**Issue by norlancd** [joshua-s/coronavirus-diary#10]
Show the application in the language of the cell phone.

Maybe you can use flutter_localizations package.

**Comment by ferndot** [comment]
👍 Definitely in support of this.

We will need to:
- [x] Add `flutter_localizations` and move all strings into an en-US locale.
- [x] Procure reviews from medical and legal experts concerning the app's copy.
- [x] Compile a list of languages to prioritize and source contributions for them. This data from the last census may help: https://www2.census.gov/library/publications/2013/acs/acs-22/acs-22.pdf

**Comment by HansMuller** [comment]
I'm the author of flutter_localizations and can help with setting up the app to be localized.

**Comment by HansMuller** [comment]
Initial i18n changes are https://github.com/coronavirus-diary/coronavirus-diary/pull/95

**Comment by HansMuller** [comment]
Add local copy of Flutter-beta gen_l10n tool so that all devs can update the app's messages: https://github.com/coronavirus-diary/coronavirus-diary/pull/102

**Comment by HansMuller** [comment]
Added the "Informed Consent" text and other user facing strings to app_en.arb: https://github.com/coronavirus-diary/coronavirus-diary/pull/139

**Comment by ferndot** [comment]
Thanks @HansMuller!

**Comment by HansMuller** [comment]
Localized country names: https://github.com/coronavirus-diary/coronavirus-diary/pull/162

**Comment by HansMuller** [comment]
Removed unused messages: https://github.com/coronavirus-diary/coronavirus-diary/pull/173

**Comment by ferndot** [comment]
@HansMuller is there any work left on this issue (for the scope of the MVP)?

**Comment by HansMuller** [comment]
We'll probably update the localizations again, but other than that, the MVP work is done.

**Comment by ferndot** [comment]
Sweet, thanks @HansMuller and @shihaohong :)
