### ISSUE TITLE
[testing] add test to ensure `gen_l10n` script has been run

### ISSUE THREAD

**Issue by christopherfujino** [joshua-s/coronavirus-diary#103]
After https://github.com/coronavirus-diary/coronavirus-diary/pull/102 lands, there should be a CI test ensuring that running `gen_l10n` does not create a diff.

I will work on this issue, though I do not have permission to assign myself.

Codemagic provides `$FLUTTER_ROOT` env var.

**Comment by christopherfujino** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
https://github.com/coronavirus-diary/coronavirus-diary/pull/102 has landed
