### ISSUE TITLE
Informed consent doesn't identify who's responsible for the app and user data

### ISSUE THREAD

**Issue by InMatrix** [joshua-s/coronavirus-diary#104]
**Describe the bug**
The informed consent doesn't say who's responsible for the app and the safekeeping of the data users uploaded. Missing this information can jeopardize the credibility of the app. 

**To Reproduce**
1. Go to the second screen of the app by clicking the button on the landing page
2. Read through the informed consent

**Expected behavior**
The informed consent should clearly identify who developed or sponsored the app both in the beginning of the consent and at the end of it.

**Comment by eethomp** [comment]
Waiting on app branding from federal agencies.

**Comment by ferndot** [comment]
@InMatrix this has been resolved by 8b6c29438ae1a7bb942ef3f1069bebb2dae7fef1. When we ship, the brand will be there.
