### ISSUE TITLE
[BUG] Not obvious that F can be changed to C on temperature screen

### ISSUE THREAD

**Issue by clocksmith** [joshua-s/coronavirus-diary#106]
**Describe the bug**
It is not obvious that F can be changed to C on the temperature screen. Using something like ToggleButtons or a dropdown Button may make it more obvious.

**To Reproduce**
1. Navigate to temperature screen (second screen of checkup)
2. Observe F button

**Screenshots**
![Screen Shot 2020-03-24 at 2 43 01 PM](https://user-images.githubusercontent.com/591699/77464593-c9428000-6ddd-11ea-8bed-c053bec0370b.png)

**Comment by joshuadeguzman** [comment]
Hi @clocksmith, I wonder if you guys would like to opt-in to using `Switch` over `ToggleButtons` to keep things simple as it is on other screens?

![2020-03-25 10-28-07 2020-03-25 10_28_16](https://user-images.githubusercontent.com/20706361/77495389-5e4b8480-6e83-11ea-98ab-5d1a4d4d1665.gif)

**Comment by dnfield** [comment]
Posted on the PR - I'm not sure a switch is the right idiom, since that's normally for `on/off` functions

**Comment by eethomp** [comment]
There's another version where we don't worry about F vs. C and collect either. It's blindingly obvious in the database which units were used.

**Comment by dnfield** [comment]
In that case why don't we just autodetect it in the UI?  We display C or F based on the input value.

**Comment by gspencergoog** [comment]
Sounds great.  I can take this one.
