### ISSUE TITLE
MVP accessibility support

### ISSUE THREAD

**Issue by norlancd** [joshua-s/coronavirus-diary#11]
Use 

- large fonts or variable size
- screen readers
- sufficient contrast

**Comment by joshua-s** [comment]
Thanks for filing this issue @norlancd. Accessibility support is absolutely critical.

**Comment by ferndot** [comment]
Thanks for filing this issue @norlancd. Accessibility support is absolutely critical.

I haven't had the bandwidth to address this yet, so feel free to hop on it. Otherwise, I will pick it up soon.

**Comment by Einarin** [comment]
I checked, and on my Android device (Galaxy S9, Android 10) changing fonts in accessibility settings correctly changes the fonts, and the Android screen reader appears to be working (I've never used it before, but I'm able to get it to read me back all the text I tested in the app).  The layout looks ugly with really large accessibility text, but everything was still functional. I'm not sure what qualifies as sufficient contrast here.

**Comment by mit-mit** [comment]
cc @clocksmith were you going to look into this?

**Comment by clocksmith** [comment]
Yes this task can be broken up into smaller tasks. I have started auditing the screen reader and text scaling, and @johnsonmh is working on contrast ratio testing

**Comment by clocksmith** [comment]
I made an a11y tag for accessibility related bugs:
https://github.com/coronavirus-diary/coronavirus-diary/issues?q=label%3Aa11y

So far everything is looking good.

**Comment by ferndot** [comment]
@clocksmith since basic a11y support is added, do you think this can be closed for the MVP?

**Comment by ferndot** [comment]
Closing since I have not heard otherwise and everything seems in line.
