### ISSUE TITLE
[BUG] Not recommended for testing with 105° temperature

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#128]
## To Reproduce ##
1. Select highest severity of all symptoms
1. Enter 105° temperature

## Expected behavior ##
Recommended for treatment

## Actual behavior ##
"You don't meet testing criteria"

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 9a4547d

**Comment by dnfield** [comment]
The application currently just returns a random value.  This is pending impelmentation of the API backend.
