### ISSUE TITLE
[Symptom Report] Replace Assessment screen with Thank You screen

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#145]
Requirements:
After completing a Symptom Report, the user should be directed to a Thank You screen
- “Thank you for submitting your data and supporting the COVID-19 response effort”
- Call to action to return to the app on the following day
- Call to action to share the app
- Button to return to the Home Screen

Acceptance criteria:
- [x] The `Assessment` model has been deleted and all references to it have been removed.
- [x] The positive and negative assessment widgets have been removed.
- [x] The Assessment screen/route has been deleted. 
- [x] A new Thank You screen has been added to the end of the Symptom Report flow (was checkup) and matches the requirements expressed above.

Wireframe:
![Record Your Symptoms](https://user-images.githubusercontent.com/1479244/77956074-2038d100-7286-11ea-8c0e-f0f3ff859f10.png)

**Comment by goderbauer** [comment]
I am in the process of ripping out the assessment model. 

With this change, can people submit as many symptoms reports per day as they want? Previously, the assessment model stored the data and it was enforced that only one report per day is made. Is that restriction removed now? Or do we need to store the date in another model?

**Comment by ferndot** [comment]
@goderbauer that restriction is now removed. The user may eventually be prompted daily to report their symptoms, but if things change (which can happen rapidly with this virus), they should be allowed to report an update.
