### ISSUE TITLE
[Symptom Report] Implement new SymptomReport data model

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#146]
The old Checkup flow is being phased out and replaced with a new Symptom Report flow. A new data model should be created to facilitate this.

Data model: https://drive.google.com/file/d/1BqJucJ-xkWmlvHmAArwvYk-TqNhXjheT/view?usp=sharing

Acceptance criteria:
- [ ] The old `Checkup` model and its related models (CheckupLocation, SubjectiveQuestionResponse, VitalsResponse) have been deleted
- [ ] A new `SymptomReport` model and related models have been created and matches the data model spec above.
- [ ] All references of the `Checkup` model have been replaced with references to `SymptomReport`.

**Comment by goderbauer** [comment]
The current model also allows only one completed symptoms report. After you've completed it, you cannot complete it a second time. I noticed this while working on https://github.com/coronavirus-diary/coronavirus-diary/pull/153.

**Comment by ferndot** [comment]
@goderbauer in the current world, the symptom report will not be retained on the device. Consequently, the bloc can be reset once the report is submitted. Does that make things easier?
