### ISSUE TITLE
[Symptom Report] Confirm the location in which the user is experiencing symptoms

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#151]
Requirements:
- After accepting the Informed Consent in the Symptom Report flow, the user should be prompted to enter the country or zip code where they are experiencing symptoms.
  - If they have already provided a country or zip code, confirm that their saved location is the location where they are experiencing symptoms.
  - The user’s selection should be persisted, but they should be given an opportunity to change it each time they enter the Symptom Report Flow.

Acceptance criteria:
- [ ] The location step in the Symptom Report Flow has been changed to confirm the user's saved location (with an option to change it) or prompt them to enter it if they have not done so already.
- [ ] The new step is shown after the Informed Consent has been accepted.

Notes:
The existing screen is excellent and can be reused with some adjustments to the language and defaults to fulfill the above criteria.

**Comment by gspencergoog** [comment]
I think I fixed this with #169. Please reopen if it isn't what was desired.
