### ISSUE TITLE
[Tutorial] Add location selector

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#156]
As per the PRD, the user will be prompted for their location in the tutorial. This should be saved to their preferences and will be used as a default in other locations in the app.

The screen currently located in the checkup/Report Symptoms flow can be reused for this. Perhaps the common elements of both screens could be unified.
![Screenshot_1585616927](https://user-images.githubusercontent.com/1479244/77976467-eb427380-72b1-11ea-94ac-6fe67180357e.png)

**Comment by gspencergoog** [comment]
I'm not quite clear: will the user be asked twice about their location, once in the tutorial, and once in the checkup? Is one for their "usual" location, and one for the location where they are when entering their checkup information?

I assume that the one in the tutorial will not happen more than once, correct? And the one in the checkup should probably default to the values set in the preferences.

**Comment by ferndot** [comment]
@gspencergoog the user will initially be prompted in the tutorial for their location. This location will be used as an app-wide default.

When the user enters the symptom report flow, they will be asked to confirm that their app-wide location is where they are experiencing symptoms (with the option to change it). Changes here will be propagated to the app-wide default.

When the user views the local statistics screen, their app-wide location will be used as a default. They can manually select other locations to view, which will be retained only for the use of this section of the app. These changes will not update the app-wide default.
