### ISSUE TITLE
[Documentation] Add json_serializable instructions to README

### ISSUE THREAD

**Issue by clocksmith** [joshua-s/coronavirus-diary#157]
In order to generate the .g.dart json files in model, I have been running:

```
find lib/src/data/models -name "*.g.dart" -type f -delete

flutter pub run build_runner build  
```

Is there a better way? If it is this or something else, it should be added to the README

**Comment by ferndot** [comment]
You can use `flutter pub run build_runner build --delete-conflicting-outputs` to build once and remove old generated files.

Or, to start a process to watch for changes and fire a rebuild:
```sh
flutter pub run build_runner watch --delete-conflicting-outputs
```
