### ISSUE TITLE
[FEATURE] Integrate with the CovidNearMe.org API

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#158]
*Important:* this API is yet to be made available. This ticket will be updated with more information once that happens.

Acceptance criteria:
- [ ] A basic API client has been added
- [x] ~~Token authentication has been implemented using the endpoint provided by CovidNearMe.org~~ We were given a static API key to keep this simple.
- [ ] The Symptom Reports repository has been modified to use the CovidNearMe.org
 API rather than dummy data

Possible package to simplify API integration: https://github.com/trevorwang/retrofit.dart/

-------

# Symptom Reporting API
_Docs sent by the CovidNearMe.org Devs_

## Sending Data In

There is (now) an API token that is sent as an authorization header along with the json submission. 

## A Code Example

This API has been tested using the standard Rails test example (code below) and by using an HTTP post tool (mechanize) (belt and suspenders) specifically to verify authentication practices.

The API token has to be submitted as an Authorization header:

    url = "http://localhost:3169/api/v1/symptom_report/create"
    agent = Mechanize.new
    result = agent.post(url, symptoms, 'Authorization' => api_token)

## Verifying that Data Got There

Login to your covidnearme.org account by going to:

    https://covidnearme.org/tools/
    
and selecting the sign in link

Go to your admin dashboard by going to:

    https://covidnearme.org/admin/
    
and selecting Symptoms from the left hand sidebar

Navigate to the last symptom and look for some bit of data specific to what you entered to confirm the data you sent (for example send the word ebola in the field for what were you tested for)

## Example request
```json
{
  "user_id": "00000000-0000-0000-0000-000000000000",
  "is_fake": true,
  "location": {
    "postal_code": "10001",
    "country": "US",
  },
  "question_responses": [
    {
      "question_identifier": "shortness_of_breath",
      "response": "none",
    },
    {
      "question_identifier": "cough",
      "response": "mild",
    },
    {
      "question_identifier": "fever",
      "response": "moderate",
    },
    {
      "question_identifier": "temperature",
      "response": "37.1",
    },
    {
      "question_identifier": "nausea",
      "response": "severe",
    },
    {
      "question_identifier": "tested_for_flu_etc",
      "response": "no",
    },
    {
      "question_identifier": "tested_positive_for_flu_etc",
      "response": "yes",
    },
    {
      "question_identifier": "tested_positive_for_what",
      "response": "no",
    },
    {
      "question_identifier": "tried_to_get_tested_for_covid19",
      "response": "yes",
    },
    {
      "question_identifier": "covid19_result",
      "response": "negative",
    }
  ]
}
```

**Comment by ferndot** [comment]
Since this initial task will only involve 2 endpoints, I put both under the scope of this issue. We can split it out if preferred.

**Comment by bkonyi** [comment]
Will this issue also encompass #7 or do we want to keep these separate?

**Comment by ferndot** [comment]
@bkonyi let's keep this separate for now. This issue is mainly focused on connecting the API client to the Symptom Reports repository. The individual consumers of the repository/blocs may need to handle errors differently.

**Comment by ferndot** [comment]
I received definition concerning this. Will be updating this issue and hooking up a basic API client.
