### ISSUE TITLE
[BUG] Health Checkup: Shortness of breath question does not show gradient scale indicators

### ISSUE THREAD

**Issue by elavenrac** [joshua-s/coronavirus-diary#17]
**Describe the bug**
When tasking the health checkup and answering the questions , the first question "Are you experiencing shortness of breath?" does not have gradient scale indicators like the other questions

**To Reproduce**
1. Open app
2. Click on [Check up on your health] button to begin survey
3. Scroll down to [Start Checkup] on the next page
4. When answering the first question there is no gradient bar on the slider

**Expected behavior**
User should see the following options for the slider.
1- Never
5- Constantly

**Screenshots**
![Screenshot_20200322-152326](https://user-images.githubusercontent.com/35881999/77258747-0af2ef80-6c53-11ea-94d7-8a40334a4475.png)

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android 9
 - App version:

**Comment by Hixie** [comment]
I'm working on this.
