### ISSUE TITLE
[Local Statistics] Screen and location selector

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#176]
Requirements:
- A Local COVID-19 Statistics Screen should be created.
  - The user should be able to manually enter a zip code or country.
  - The default selected location should be determined by the following rules:
    - If the user provided a location in the tutorial, that value should be used by default.
    - Otherwise, if the user’s recent locations list is not empty, the most recent location should be used by default.
     - Otherwise, the location should be blank and the Local COVID-19 Statistics Screen should display a “Select a location” message instead of its regular contents.
  - The user should be able to select a zip code or country from a list of recent locations.
    - A maximum of 5 locations should be remembered.
    - When a user selects a location, it should be saved to their list of recent locations.
This should include the initially selected location.

**Comment by bkonyi** [comment]
Some things have come up  so I'm going to unassign myself for now as to not block work on this feature. Will come back to it if it's still here when I find some time.

**Comment by ferndot** [comment]
@bkonyi thanks for the update.
