### ISSUE TITLE
[Local Statistics] Totals

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#177]
Requirements:
- The Local Statistics screen should display Cases, Deaths, and Recoveries totals.

**Comment by clocksmith** [comment]
How will the totals be determined? The data from Locations API only gives counts per day since 3/22/20. If that is to be summed, won't it be an incomplete total?

**Comment by ferndot** [comment]
@clocksmith I added some clarification about this to the API issue. These numbers are totals rather than daily case/death/recovery counts.

**Comment by ferndot** [comment]
@clocksmith are you still planning on working on this?
