### ISSUE TITLE
[BUG] Start screen has no call to action if it's scrolled off the screen

### ISSUE THREAD

**Issue by Hixie** [joshua-s/coronavirus-diary#20]
![Screenshot_20200322-142945](https://user-images.githubusercontent.com/551196/77261172-d3337a00-6c49-11ea-8fd2-70ea7871d63b.png)

**Comment by Hixie** [comment]
This is the current portrait version:
![Screenshot_20200322-160104](https://user-images.githubusercontent.com/551196/77263865-77bbb900-6c56-11ea-923a-91a3725b2bfe.png)

**Comment by javierlopez288** [comment]
We could try splitting both content containers, so we can do this?
<img width="658" alt="layout" src="https://user-images.githubusercontent.com/5491390/77269981-ca51a100-6c67-11ea-92f0-9b92af1f3e2e.png">

**Comment by willlarche** [comment]
That is preferred. Scroll indicator is brute force solution (#38 ).

**Comment by Hixie** [comment]
That just seems to make the problem worse -- what if there's not enough horizontal space either?
