### ISSUE TITLE
[BUG] "Click here to learn more" vs "Thanks for offering to help out!"

### ISSUE THREAD

**Issue by Hixie** [joshua-s/coronavirus-diary#21]
The start screen has a button labeled "Click here to learn more" which is not a strong call to action.
The screen that appears if you click it says "Thanks for offering to help out!" which doesn't really match the call to action (the user just wanted to learn more, they didn't offer to help out).

**Comment by ferndot** [comment]
The copy on that screen is definitely not optimized for the app. It was developed for CovidNearMe.org and refers to the "website" and a "browser bookmark".

Working to get an updated version...

**Comment by ferndot** [comment]
This has been sorted out in the new informed consent that will be merged soon. Closing!
