### ISSUE TITLE
[FEATURE] Accept temperature in Celsius 

### ISSUE THREAD

**Issue by Hixie** [joshua-s/coronavirus-diary#26]
On the "Take your temperature" screen there's no way to specify the temperature in Celsius.

**Comment by bkonyi** [comment]
I can take this one.

**Comment by bkonyi** [comment]
Got something mocked up:

![image](https://user-images.githubusercontent.com/24210656/77268003-b9059600-6c61-11ea-95f8-e57f9f303f3a.png)

![image](https://user-images.githubusercontent.com/24210656/77268009-bf940d80-6c61-11ea-9caf-0fc2bac4903c.png)
 
![image](https://user-images.githubusercontent.com/24210656/77268013-c458c180-6c61-11ea-92a3-f186656f85fc.png)

![image](https://user-images.githubusercontent.com/24210656/77268061-ec482500-6c61-11ea-905c-784ef192dd77.png)
