### ISSUE TITLE
[BUG] First page of Your Health Checkup doesn't make it clear you need to scroll

### ISSUE THREAD

**Issue by Hixie** [joshua-s/coronavirus-diary#29]
![Screenshot_20200322-151116](https://user-images.githubusercontent.com/551196/77261945-75099580-6c4f-11ea-95a4-61cc672d5c7a.png)

**Comment by Hixie** [comment]
Also a problem when the foot is present (see #30):
![Screenshot_20200322-151936](https://user-images.githubusercontent.com/551196/77262087-9919a680-6c50-11ea-8ea8-ab7fb1e46345.png)

You can press "Continue" without ever scrolling down to the question about the fever.

**Comment by willlarche** [comment]
Footer needs an elevation and probably a different background color (white?)
