### ISSUE TITLE
[FEATURE] Handle case where user does not consent to the terms

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#31]
**Is your feature request related to a problem? Please describe.**
When the user does not consent to the app's usage terms, there is no additional information provided.

**Describe the solution you'd like**
Implement a new screen that notifies the user that they have not consented and will not be able to use the app. Phrase it much better than that :D

**Comment by Hixie** [comment]
See also https://github.com/coronavirus-diary/coronavirus-diary/issues/22

**Comment by joshua-s** [comment]
Resolving as a duplicate of #22

**Comment by JoseAlba** [comment]
I was wondering if another page is necessary it might make more sense to use a [dialog](https://api.flutter.dev/flutter/material/Dialog-class.html) if the message is short.
