### ISSUE TITLE
[BUG] Footer and scroll view overlap on Health Checkup screen

### ISSUE THREAD

**Issue by Hixie** [joshua-s/coronavirus-diary#33]
![Screenshot_20200322-153529](https://user-images.githubusercontent.com/551196/77262418-eac33080-6c52-11ea-97f4-63f958c41d1e.png)

**Comment by Hixie** [comment]
this may be fixed on develop, i was on master when i saw this

**Comment by bkonyi** [comment]
This appears to be fixed on `develop`.

**Comment by mit-mit** [comment]
Closing per above comment, @Hixie please reactivate if you see this again
