### ISSUE TITLE
[BUG] "It's time for your checkup" screen doesn't scroll (and overflows)

### ISSUE THREAD

**Issue by Hixie** [joshua-s/coronavirus-diary#34]
![Screenshot_20200322-152754](https://user-images.githubusercontent.com/551196/77262439-01698780-6c53-11ea-9923-db6a14f8d4c9.png)

**Comment by Hixie** [comment]
this is probably fixed on develop, i was on master when i saw this

**Comment by goderbauer** [comment]
This particular issue is fixed on develop. Closing.
