### ISSUE TITLE
[BUG] Inconsistent use of "Zip Code" and "Postal Code"

### ISSUE THREAD

**Issue by bkonyi** [joshua-s/coronavirus-diary#35]
**Describe the bug**
"Thanks for offering to help out!" says "Total daily cases for zip codes will be..." but the "Your Health Checkup" page says "We will collect your postal code".

**Expected behavior**
"zip code" vs "postal code" should either be populated based on user country, or be fixed to "zip code"
**Screenshots**

**Comment by willlarche** [comment]
Expected behavior above is good idea. Removing UX/UI since there is no need for designer intervention (bug is ready for dev.)
