### ISSUE TITLE
[FEATURE] Scroll more indicator

### ISSUE THREAD

**Issue by willlarche** [joshua-s/coronavirus-diary#38]
Fixes #20 
Fixes #29 
Related to #34 

Theming:
Typography: Button
Icon: expand_more
Color: Same as body text on that screen

Behavior:
1. Appears when any screen is not scrolled to the end
2. Tappability is a nice to have. (Scroll a page height on tap)
3. Can exist OUTSIDE the safe area.
4. Disappears when scrolled to the end.

![Scroll More](https://user-images.githubusercontent.com/1271525/77266954-6fc04100-6c77-11ea-861e-e325c9a5847a.png)

**Comment by dnfield** [comment]
Would a FAB be appropriate for some of these screens?

**Comment by willlarche** [comment]
What would be best for some of them is redoing layout to not need to scroll for sure which means we should look at all the layouts for optimizations like that. But there will also be ones that can't be rejiggered enough to avoid scroll. This solves it brute force first getting us unstuck.

**Comment by Hixie** [comment]
Any ideas for making the text readable on this screen?:
![Screenshot_20200323-112828](https://user-images.githubusercontent.com/551196/77350356-a048bf00-6cf9-11ea-94d1-82efcb183977.png)

**Comment by willlarche** [comment]
I'd say that this screen "Concerned about your health" doesn't need the scroll more indicator. It has an interrupted element (the lighter blue region) which is the hint to the user to scroll. We should use the scroll more indicator on pages where we're positive people won't find a CTA without it.

**Comment by willlarche** [comment]
And we should use it conservatively. Research points to people knowing to scroll: https://uxmyths.com/post/654047943/myth-people-dont-scroll

**Comment by Hixie** [comment]
This is the same screen on a different display:
![Screenshot_20200323-115126](https://user-images.githubusercontent.com/551196/77352632-b99f3a80-6cfc-11ea-9fc1-8e4aff7fba88.png)

**Comment by Hixie** [comment]
This isn't about people not scrolling, it's about people not knowing there's content to scroll to. The article above is mostly about pages like magazine articles where it's obvious that there's more content.

**Comment by willlarche** [comment]
Good point!
