### ISSUE TITLE
[FEATURE] Take your Temperature Help Modal Content

### ISSUE THREAD

**Issue by amweinstein** [joshua-s/coronavirus-diary#43]
CDC advises people to wait 30 mins after eating drinking or exercising before taking their temp AND waiting at least 6 hours after taking meds that could lower your temp. We may want to consider including these tips in our "How to take your Temp" help modal to prevent false positives/negatives. 

Get to the modal by tapping "Need Help? Click for Instructions" on Take your Temperature screen. 

[**Link to PDF with CDC instructions for taking your temp](https://www.cdc.gov/coronavirus/2019-ncov/downloads/COVID-19_CAREKit_ENG.pdf)**

![49149](https://user-images.githubusercontent.com/44853073/77272255-025be280-6c6e-11ea-93e3-07bc6297a9cc.jpg)

**Comment by mit-mit** [comment]
I created a tentative fix for this
