### ISSUE TITLE
[BUG] App fails to run on iOS

### ISSUE THREAD

**Issue by mit-mit** [joshua-s/coronavirus-diary#48]
**Describe the bug**
App fails to `flutter run` against iOS Simulator

**To Reproduce**
1. clone repo
1. start iOS simulator
1. `flutter run`

=>
```console
$ flutter run -d iP

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Running Xcode build...

 ├─Assembling Flutter resources...                           5.3s
 └─Compiling, linking and signing...                         8.3s
Xcode build done.                                           19.2s
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPhone 11 Pro Max.
```

**Expected behavior**
App launches.

**Smartphone (please complete the following information):**

iOS simulator `Version 11.3.1 (SimulatorApp-912.5.1 SimulatorKit-570.3 CoreSimulator-681.17.2)` running an iPhone 11 Pro Max

**Additional context**

```
$ flutter --version
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (6 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

**Comment by mit-mit** [comment]
This appears to only repo on the `develop` branch, not on the `master` branch (you have to run `flutter clean` after switching to the develop branch to get the repro).

**Comment by mit-mit** [comment]
I'm speculating this is caused by https://github.com/coronavirus-diary/coronavirus-diary/commit/444209de6ef49ace885196b244aaaec3aa4f5154 as per discussion in https://github.com/flutter/flutter/issues/41793

**Comment by mit-mit** [comment]
PR in https://github.com/coronavirus-diary/coronavirus-diary/pull/49

cc @jmagman did I get this right?

**Comment by jmagman** [comment]
Yup! (I really need to fix that...)
