### ISSUE TITLE
[FEATURE] Desktop support

### ISSUE THREAD

**Issue by JoseAlba** [joshua-s/coronavirus-diary#50]
**Is your feature request related to a problem? Please describe.**
Add Desktop support to the existing application.

**Describe the solution you'd like**
Will check the the smallest side of the application once the application reaches a certain breakpoint. It will switch to the desktop version of the application.

**Comment by gspencergoog** [comment]
I'm happy to work on anything Desktop related.

**Comment by JoseAlba** [comment]
Because a website already exist for this application we are planning on devoting our time to more critical task.

The website URL: http://covidnearme.org/ 

What is the plan for distribution on the desktop side of things?
What are some values added to the desktop?
Plus a lot of the plugins don't have support for desktop like the GPS tracker and the share plugin.

Future goals [optional if you have the time]: 
1. Enable all versions of the application.
             a. Web
             b. Desktop (OSX, Windows, Linux)
2. The "Share now" button isn't all that useful on desktop. We should probably switch it to use url_launcher.
3. Add Focus support
            a. Focus highlights should be more prominent for buttons.
            b. No focus yet for sliders (which is a big deal, since we don't have it yet on master).
            c. Initial autofocus not being set to a sensible thing.
4. Make sure that internationalization and accessibility works with Desktop view too. 
5. Geolocation would have to be replaced with a zip code entry field.
