### ISSUE TITLE
[BUG] Unusual use of the trash icon

### ISSUE THREAD

**Issue by InMatrix** [joshua-s/coronavirus-diary#57]
**Describe the bug**
The meaning of the trash icon is unclear in the screenshot below. Since clicking the icon takes the user back to the welcome screen, a back icon or a close icon can probably better signifier this action. 

**To Reproduce**
1. Go through the welcome and user agreement screens
2. Click the "Click here to get started" button in the following screen
3. Examine the next screen titled "CovidNearMe"

**Expected behavior**
The trash icon usually signifies deleting an object in user interfaces.

**Screenshots**
![image](https://user-images.githubusercontent.com/348942/77341725-64f3c380-6cec-11ea-807f-e4d4cd261519.png)

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - OS: iOS 13
 - App version: Not sure how to get the app version. I used the latest version on the develop branch.

**Comment by bkonyi** [comment]
This button is for debug purposes and won't appear in release builds, so I wouldn't be too concerned about the icon usage. It's just an easy way to clear the state of the app.

**Comment by InMatrix** [comment]
Why not just do a hot restart?
