### ISSUE TITLE
[BUG] Unnecessary 'get started' screen

### ISSUE THREAD

**Issue by InMatrix** [joshua-s/coronavirus-diary#59]
**Describe the bug**
The 'get started' screen after the user agreement seems to be unnecessary, since the next screen provides sufficient instructions to the user.
![image](https://user-images.githubusercontent.com/348942/77344686-c158e200-6cf0-11ea-92db-3454c3e21e94.png)

**Comment by JoseAlba** [comment]
Have we decided to keep this page ?  The page does look a lot cleaner now but it is still not necessary.
