### ISSUE TITLE
[FEATURE] Fallback if location services are disabled or user rejects location

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#6]
**Is your feature request related to a problem? Please describe.**
Location services may be disabled on some devices. Users may also reject the location permission. There is currently no fallback.

**Describe the solution you'd like**
A dialog pops up that allows the user to enter their zip code. The zip code is both added to the checkup and saved to local storage for later use (use Preferences).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cyanglaz** [comment]
I'll start working on this to get the hang of the app! :) 

Didn't see a PR is open for this. Will look for a different issue to work on.

**Comment by ferndot** [comment]
Closing. As per the new scope for v1.0, we will not be using location services.
