### ISSUE TITLE
[BUG] UX issues around the tutorial flow

### ISSUE THREAD

**Issue by xster** [joshua-s/coronavirus-diary#69]
**Describe the bug**
If the consent/tutorial screens are meant to force a decision before the user starts using the app, it shouldn't be a second page on the navigator. Currently, you can simply press the back button on Android to dismiss the whole sequence. 

It's also confusing if the user got there accidentally and is looking to get back to the welcome page but it can't be navigated to anymore once dismissed (the trash icon actually navigating back to the welcome flow might be even more confusing 🙂). 

Consider using https://api.flutter.dev/flutter/widgets/Navigator/pushReplacement.html and replacing the root welcome page instead of letting the welcome page be a second page and popping it at the end of the welcome flow. 

It's also currently possible to choose "No!" (https://github.com/coronavirus-diary/coronavirus-diary/issues/22), then still use the app by pressing the Android back button.

**Comment by aadarsh-patel** [comment]
This issue has been resolved by #124 .
