### ISSUE TITLE
Handle server failures

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#7]
**Describe the bug**
When the process of submitting data to the server fails, the app does not handle it gracefully. 

**To Reproduce**
1. Start checkup
2. Disconnect internet connection
3. Navigate to 2nd checkup step

**Expected behavior**
1. Check internet connection
   1. If not present, notify user
2. Send request again
3. If continues to fail, notify user

**Screenshots**
N/A

**Smartphone (please complete the following information):**
All

**Additional context**
N/A

**Comment by mayoreee** [comment]
I'm on it

**Comment by bkonyi** [comment]
> I'm on it

@egbinola this issue is already assigned to me and I've started work on this.

**Comment by mayoreee** [comment]
Alright @bkonyi

**Comment by ferndot** [comment]
@bkonyi are you still working on this?

**Comment by bkonyi** [comment]
I can still, was just waiting for some networking code to be in place :-)

**Comment by ferndot** [comment]
@bkonyi sweet! It should be ready. We are just using a couple endpoints (report submission and local statistics). If you go to the discord, I can send you a testing api key.
