### ISSUE TITLE
[BUG] textScaleFactor > ~2.5 cuts off floating continue button on checkup screen

### ISSUE THREAD

**Issue by clocksmith** [joshua-s/coronavirus-diary#70]
**Describe the bug**
The text of "Step N/2" is too big and causes the button to the right to overflow.

textScaleFactor = 3
![original3](https://user-images.githubusercontent.com/591699/77370148-9db88a80-6d36-11ea-9090-ada9aff231f1.png)

**To Reproduce**
1. Set textScaleFactor to 3 with MediaQuery
2. Navigate to checkup screen and scroll down to see continue button
3. Observe that the "continue" button is overflowing

**Expected behavior**
It does not overflow

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL (although it probably happens on a majority of devices
 - OS: Android 10 
 - App version 1.4.2

**Comment by gspencergoog** [comment]
This is no longer the case, closing.
