### ISSUE TITLE
First screen isn't actionable

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#71]
## Context ##
The first screen doesn't give the user enough context to understand what this app is.  The list items look like they could be buttons.

## Suggestions ##
- [ ] Simplify the heading.  "The CovidNearMe App" is a weird name for a product.  Can we just say "Welcome to CovidNearMe."?
- [ ] Add a heading that provides context to the feature list:

    "CovidNearMe is a US Centers for Disease Control project to help the public respond to the novel coronavirus (COVID-19).  It allows you to:"
- [ ] Change the button copy to "Get started"

## Screenshot ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipOUHVbyVSTDUL5frFr9CdHq9fJsgj3w0ppwfN2X?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

**Comment by javierlopez288** [comment]
+1 I think a brief explanation upfront would be super helpful
