### ISSUE TITLE
App bar trash can deletes app state with no warning

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#77]
## Context ##
There's an unlabeled trash button in the app bar.  Tapping it resets the app to the beginning.

(The more I think about it, the more I suspect it must be debug-only.  Otherwise, it's not clear what the ramifications are: is the user deleting their data?  Is the server copy deleted?)

## Suggestions ##
- Can we remove this button?  I can't think of any other app that lets you clear your cache from the main screen.
- If it's debug-only, make it an ugly color (like #FF0000) to make it obvious that it isn't part of the app.
- Add a warning dialog: "Do you want to clear all your data?"
- Move it out of the app bar into the body (and make it more subtle than the other sections/buttons) "Want to leave this project?"

## Screenshot ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipOSsY0b_tEV8p2JypnRfpKIzpzBwFErCZBLupu7?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

**Comment by ferndot** [comment]
The button is indeed debug-only. I wouldn't put too much effort into it, but relocating it into the body with a clear description ("DEBUG: Clear all saved data") sounds like a quick improvement.
