### ISSUE TITLE
APP_LINK in share text

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#78]
## Describe the bug ##
The Share button literally includes the text `APP_LINK`

## To Reproduce ##
1. Tap Share Now from the main screen.

## Expected behavior ##
There's a link that takes the user to CovidNearMe.  Instead it says "APP_LINK"

## Screenshots ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipNhIe1txl_B6BHmh3cN6vJpVyPCB2mum4zzAyD_?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

**Comment by joshua-s** [comment]
Is there a good way to generate this? Or, does it need to be hardcoded?

**Comment by ferndot** [comment]
@appsforartists fixed in #194
