### ISSUE TITLE
"We will collect your zip code" should remind users they are anonymous

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#79]
## Context ##
On the Your Health Checkup screen, a switch tells users "We will collect your zipcode."

## Suggestion ##
- Remind users they are anonymous: "We will collect your ZIP Code, but **you will still be anonymous.**"

## Screenshot ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipMUJOD089jjjsr2Oh1xgOV1_qjqbXQEz7qYWv3e?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

**Comment by ferndot** [comment]
Thanks for reporting this @appsforartists. That particular UI element has now been removed and the app has also been updated to remind folks that they are anonymous on multiple screens!
