### ISSUE TITLE
[BUG] Prompted for location with no context

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#80]
## Describe the bug ##
Your Health Checkup asks for my precise location without giving me any context.  This violates my expectation of privacy, which has been set up through the rest of the flow.  Informed Consent says I'm anonymous, and the previous page only says my ZIP Code will be collected.

## To Reproduce ##
1. Tap Check up on your health
1. Tap Start checkup

## Expected behavior ##
No permissions dialog appears without warning me what is being asked for, how it will be used, and why I should consider approving it.

## Screenshots ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipMUJOD089jjjsr2Oh1xgOV1_qjqbXQEz7qYWv3e?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

**Comment by ferndot** [comment]
Thank you for reporting this! As per the new requirements for v1.0, location services will not be used and this can be closed.
