### ISSUE TITLE
Submitting with no temperature doesn't allow you to add one later

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#82]
## Context ##
If I complete a health checkup without a temperature, it tells me "You have completed your checkup for today!"  

I'm surprised that temperature is a requested field, but there's no way for me to submit it later.  I also wonder what happens if I develop severe symptoms later in the day, after I've already completed the survey.

I don't know if this is intentional (to prevent people from gaming the system by changing their answers until they get a test), but it's an unexpected user experience.

## Screenshot ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipN95cJDwQAv0gthHSkhr39XynMrp25eRJXj1_oI?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

**Comment by cyanglaz** [comment]
I will add a popup to block user from continuing if the temperature is not entered.

**Comment by cyanglaz** [comment]
A note on UX: I think we might also want to force user to take action on the symptom/subjective page. There were times that I didn't even notice the page and hit continue.
Instead of select no symptom by default, we should force user to select a value. Going to raise an issue for this.

**Comment by ferndot** [comment]
Hold off on this one for the moment please. I need to confirm expected functionality here.

**Comment by JoseAlba** [comment]
Any follow up?

**Comment by ferndot** [comment]
Yeah. Updated functionality is that the user will not be able to change their symptom reports once they have been submitted. However, the user will be able to submit more than one report in a day.

**Comment by ferndot** [comment]
As per the above comment, this issue is resolved.
