### ISSUE TITLE
[BUG] UX: affordance not clear on how to make the checkup screen advanceable

### ISSUE THREAD

**Issue by xster** [joshua-s/coronavirus-diary#85]
**Describe the bug**
Turn off internet (to simulate poor connectivity), go to the health checkup page. There's no page advancement UI at the bottom of the page. There's no loading indicator showing something is in progress either. It looks like it's in a final state and doesn't look like the user can do anything to progress at this point. 

https://streamable.com/lk7mw

**Comment by ferndot** [comment]
This is now resolved!
