### ISSUE TITLE
[BUG] The NO button - it does nothing!

### ISSUE THREAD

**Issue by appsforartists** [joshua-s/coronavirus-diary#86]
## To Reproduce ##
1. Tap No on the Informed Consent screen

## Expected behavior ##
I'm warned that I cannot participate without accepting, and told to either delete the app or accept the terms.

## Actual behavior ##
There's a red X on the No button, but no other apparent changes.

## Screenshots ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipP1eWxVKAYjXSGJJh3p8hqI0tVVSI3vTV5gKxFG?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

**Comment by xster** [comment]
Same as https://github.com/coronavirus-diary/coronavirus-diary/issues/22
