### ISSUE TITLE
[BUG] UX: your personalized assessment page should have clearer, consistent flows

### ISSUE THREAD

**Issue by xster** [joshua-s/coronavirus-diary#91]
**Describe the bug**

After completing the questionnaire, the results page has no buttons but can be exited via the appbar back button and the Android back button. Both affordances seem like escape hatches rather than affirmative actions saying you're done here. Consider removing the appbar back button and adding a button at the bottom saying "got it" or some such. 

Upon navigating back to the same page, the results page's appbar no longer has a back button and can only be exited via the Android back button.

**Comment by ferndot** [comment]
As per the new PRD, there will not be an assessment page. Closing this.
