### ISSUE TITLE
[BUG] UX: subjective page should not select slider values by default.

### ISSUE THREAD

**Issue by cyanglaz** [joshua-s/coronavirus-diary#96]
**Describe the bug**
On the subjective page, by default, the sliders are selected with the lowest value. User might hit continue quickly and miss this page. It might be better to force user select a value.

**To Reproduce**
1. Go to 'home'
1. Click on 'Check up on your health'
1. Click on 'Start checkup'
1. See that the sliders are selected

**Expected behavior**
We should force user to select a value so they don't miss this page.

**Screenshots**
<img width="304" alt="Screen Shot 2020-03-23 at 6 36 27 PM" src="https://user-images.githubusercontent.com/3756895/77379287-90e76700-6d35-11ea-8aae-018c0db2dd66.png">

related to https://github.com/coronavirus-diary/coronavirus-diary/issues/82

**Comment by gspencergoog** [comment]
How would this work, exactly?

Maybe add a new minimum value that is labeled with an icon like ">>" or something, and default to that, and refuse to go forward if they haven't moved it off of that?

Or, maybe a semitransparent button over the slider that when clicked goes away, and they can't hit submit until they've done that for all the values? I guess that's not ideal because the slider has to start with some kind of value or there isn't a thumb to drag.

**Comment by cyanglaz** [comment]
Per https://github.com/coronavirus-diary/coronavirus-diary/pull/98#issuecomment-604815684
All fields should be optional so we shouldn’t block the flow.

Maybe we should make the default slider value as some sort of “N/A”. This way we know when the value is “no coughing”, it is explicitly selected by the user.

**Comment by eethomp** [comment]
Set the defaults to "no" for the first visit. It occurs to me that we may want to retrieve & display the previous visit's symptoms through an API to set defaults for the next round of data entry. What do you think?

**Comment by gspencergoog** [comment]
Here's what my PR looks like.  Is that sort of what you were imagining?

![image](https://user-images.githubusercontent.com/8867023/77775589-f6737600-7009-11ea-95d7-85b918aff46b.png)

**Comment by cyanglaz** [comment]
Yes. I personally like this better over the previous slider approach.

**Comment by gspencergoog** [comment]
It has the advantage of not having a default value.

**Comment by ferndot** [comment]
That is really nice!
